<!DOCTYPE INFO [
<!ELEMENT INFO (COPIRIGHT, COUNTRY, YEAR, NAME, SURNAME)>
<!ELEMENT COPIRIGHT (#PCDATA)>
<!ELEMENT COUNTRY (#PCDATA)>
<!ELEMENT YEAR (#PCDATA)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT SURNAME (#PCDATA)>
]>
<INFO>
    <COPIRIGHT>Все права защищены</COPIRIGHT>
    <COUNTRY>Беларусь, Минск</COUNTRY>
    <YEAR>2017</YEAR>
    <NAME>Родион</NAME>
    <SURNAME>Алексеенко</SURNAME>
</INFO>